# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_mainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow_SignalViewer(object):
    def setupUi(self, mainWindow_SignalViewer):
        mainWindow_SignalViewer.setObjectName("mainWindow_SignalViewer")
        mainWindow_SignalViewer.resize(894, 607)
        self.centralwidget = QtWidgets.QWidget(mainWindow_SignalViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grpbx_signal_table = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbx_signal_table.setMaximumSize(QtCore.QSize(300, 16777215))
        self.grpbx_signal_table.setObjectName("grpbx_signal_table")
        self.gridLayout = QtWidgets.QGridLayout(self.grpbx_signal_table)
        self.gridLayout.setObjectName("gridLayout")
        self.tbl_signals = QtWidgets.QTableView(self.grpbx_signal_table)
        self.tbl_signals.setObjectName("tbl_signals")
        self.gridLayout.addWidget(self.tbl_signals, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.grpbx_signal_table)
        self.grpbx_signal_viewers = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbx_signal_viewers.setObjectName("grpbx_signal_viewers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grpbx_signal_viewers)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_signal_viewers = QtWidgets.QGridLayout()
        self.grid_signal_viewers.setObjectName("grid_signal_viewers")
        self.gridLayout_2.addLayout(self.grid_signal_viewers, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.grpbx_signal_viewers)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        mainWindow_SignalViewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow_SignalViewer)
        self.statusbar.setObjectName("statusbar")
        mainWindow_SignalViewer.setStatusBar(self.statusbar)
        self.actionOpen_file = QtWidgets.QAction(mainWindow_SignalViewer)
        self.actionOpen_file.setVisible(True)
        self.actionOpen_file.setObjectName("actionOpen_file")

        self.retranslateUi(mainWindow_SignalViewer)
        QtCore.QMetaObject.connectSlotsByName(mainWindow_SignalViewer)

    def retranslateUi(self, mainWindow_SignalViewer):
        _translate = QtCore.QCoreApplication.translate
        mainWindow_SignalViewer.setWindowTitle(_translate("mainWindow_SignalViewer", "MainWindow"))
        self.grpbx_signal_table.setTitle(_translate("mainWindow_SignalViewer", "Plot Items"))
        self.grpbx_signal_viewers.setTitle(_translate("mainWindow_SignalViewer", "Signal View"))
        self.actionOpen_file.setText(_translate("mainWindow_SignalViewer", "Open file     Ctrl+O"))
        self.actionOpen_file.setIconText(_translate("mainWindow_SignalViewer", "Open file"))
        self.actionOpen_file.setToolTip(_translate("mainWindow_SignalViewer", "Open file     Ctrl+O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow_SignalViewer = QtWidgets.QMainWindow()
    ui = Ui_mainWindow_SignalViewer()
    ui.setupUi(mainWindow_SignalViewer)
    mainWindow_SignalViewer.show()
    sys.exit(app.exec_())
