# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignalViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewer(object):
    def setupUi(self, viewer):
        viewer.setObjectName("viewer")
        viewer.resize(777, 414)
        self.gridLayout_2 = QtWidgets.QGridLayout(viewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(viewer)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(self.widget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_openfile = QtWidgets.QPushButton(self.widget)
        self.btn_openfile.setObjectName("btn_openfile")
        self.horizontalLayout.addWidget(self.btn_openfile)
        self.btn_play_pause = QtWidgets.QPushButton(self.widget)
        self.btn_play_pause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Play button Png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play_pause.setIcon(icon)
        self.btn_play_pause.setObjectName("btn_play_pause")
        self.horizontalLayout.addWidget(self.btn_play_pause)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(viewer)
        QtCore.QMetaObject.connectSlotsByName(viewer)

    def retranslateUi(self, viewer):
        _translate = QtCore.QCoreApplication.translate
        viewer.setWindowTitle(_translate("viewer", "Form"))
        self.btn_openfile.setText(_translate("viewer", "Open File"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewer = QtWidgets.QWidget()
    ui = Ui_viewer()
    ui.setupUi(viewer)
    viewer.show()
    sys.exit(app.exec_())
